# Generated by Django 4.2.20 on 2025-03-13 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("Locationid", models.AutoField(primary_key=True, serialize=False)),
                ("locationname", models.CharField(max_length=50)),
                ("locationaddress", models.CharField(max_length=50)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                ("Roomid", models.AutoField(primary_key=True, serialize=False)),
                ("roomname", models.CharField(max_length=50)),
                ("roomtype", models.CharField(max_length=50)),
                ("availability", models.BooleanField(default=True)),
                ("price", models.FloatField(default=0)),
                ("is_detective_light", models.BooleanField(default=False)),
                ("is_defective_chair", models.BooleanField(default=False)),
                ("is_defective_socket", models.BooleanField(default=False)),
                (
                    "Locationid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rentals.location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("Reviewid", models.AutoField(primary_key=True, serialize=False)),
                ("rating", models.IntegerField(default=5)),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "Customerid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                    ),
                ),
                (
                    "Roomid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rentals.room"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rental",
            fields=[
                ("Rentalid", models.AutoField(primary_key=True, serialize=False)),
                ("rent_start_time", models.DateTimeField()),
                ("rent_end_time", models.DateTimeField()),
                ("charge", models.FloatField(default=0)),
                ("paymentstatus", models.BooleanField(default=False)),
                (
                    "Customerid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                    ),
                ),
                (
                    "Roomid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rentals.room"
                    ),
                ),
            ],
        ),
    ]
