# Generated by Django 4.2.20 on 2025-03-18 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rental",
            name="rent_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="room",
            name="is_defective_wifi",
            field=models.BooleanField(default=False),
        ),
    ]
