# Generated by Django 4.2.20 on 2025-03-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0002_rental_rent_date_room_is_defective_wifi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="roomtype",
            field=models.CharField(max_length=20),
        ),
    ]
