# Generated by Django 4.2.20 on 2025-03-18 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0004_remove_room_roomname_alter_room_roomtype"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="is_detective_light",
            new_name="is_defective_light",
        ),
    ]
