# Generated by Django 4.2.20 on 2025-03-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0005_rename_is_detective_light_room_is_defective_light"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rental",
            name="paymentstatus",
        ),
        migrations.AddField(
            model_name="rental",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
