# Generated by Django 4.2.20 on 2025-03-19 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0007_rental_paymentstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rental",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
